# language
language: node_js
node_js: 12.16.3
cache: npm


install:
    - npm install
    
# tasks
scripts: 
    - npm run lint

    
services:
    - docker
    
    before_install:
    - npm run buildDocker
    - npm run dockerLogin
    - npm run dockerTag
    
    script:
    - npm run dockerPush
    - bundle exec rake test
