# language
language: node_js
node_js: 12.16.3
cache: npm


install:
    - npm install
    
    jobs:
        include:
        - stage: test
            script: npm run lint
        - stage: build
            script: npm run buildDocker
        - stage: deploy
            script: npm run dockerLogin
            script: npm run dockerTag
            script: npm run dockerPush
            on:
                branch: master

# tasks
# scripts: 
#     - npm run lint
    

# deploy:
#     scripts: 
#         - npm run buildDocker
#         - npm run dockerLogin
#         - npm run dockerTag
#         - npm run dockerPush
#     on:
#         branch: master
