# language
language: node_js
node_js: 12.16.3
cache: npm

branches:
    only:
    - master

# installation
install: 
    npm install

# tasks
# scripts: 
#     - npm run lint
    

# deploy:
#     scripts: 
#         - npm run buildDocker
#         - npm run dockerLogin
#         - npm run dockerTag
#         - npm run dockerPush
#     on:
#         branch: master


jobs:
    include:
        - stage: test
        script: npm run lint       
        
        - stage: deploy
        # require the branch name to be master (note for PRs this is the base branch name)
        if: branch = master
        script: npm run buildDocker
        script: npm run dockerLogin
        script: npm run dockerTag
        script: npm run dockerPush